name: Netlify QA Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Netlify (QA)
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: .next
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "QA deploy from main branch"
          netlify-auth-token: ${{ secrets.NETLIFY_QA_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_QA_SITE_ID }}
        env:
          NODE_VERSION: 20
