name: Upload Highlight Sourcemaps

on:
  push:
    branches:
      - main
      - highlight-io
      - highlight-sourcemaps
  workflow_dispatch:

jobs:
  upload-sourcemaps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install react-email dependencies
        run: |
          cd src/react-email
          npm install

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Upload Highlight sourcemaps
        env:
          HIGHLIGHT_API_KEY: ${{ secrets.HIGHLIGHT_API_KEY }}
        run: |
          npx @highlight-run/sourcemap-uploader upload \
            --apiKey "$HIGHLIGHT_API_KEY" \
            --path .next
